const countries = [
    { name: 'Afghanistan', abbr: 'AF', flag: '🇦🇫' },
    { name: 'Aland Islands', abbr: 'AX', flag: '🇦🇽' },
    { name: 'Albania', abbr: 'AL', flag: '🇦🇱' },
    { name: 'Algeria', abbr: 'DZ', flag: '🇩🇿' },
    { name: 'American Samoa', abbr: 'AS', flag: '🇦🇸' },
    { name: 'Andorra', abbr: 'AD', flag: '🇦🇩' },
    { name: 'Angola', abbr: 'AO', flag: '🇦🇴' },
    { name: 'Anguilla', abbr: 'AI', flag: '🇦🇮' },
    { name: 'Antarctica', abbr: 'AQ', flag: '🇦🇶' },
    { name: 'Antigua and Barbuda', abbr: 'AG', flag: '🇦🇬' },
    { name: 'Argentina', abbr: 'AR', flag: '🇦🇷' },
    { name: 'Armenia', abbr: 'AM', flag: '🇦🇲' },
    { name: 'Aruba', abbr: 'AW', flag: '🇦🇼' },
    { name: 'Australia', abbr: 'AU', flag: '🇦🇺' },
    { name: 'Austria', abbr: 'AT', flag: '🇦🇹' },
    { name: 'Azerbaijan', abbr: 'AZ', flag: '🇦🇿' },
    { name: 'Bahamas', abbr: 'BS', flag: '🇧🇸' },
    { name: 'Bahrain', abbr: 'BH', flag: '🇧🇭' },
    { name: 'Bangladesh', abbr: 'BD', flag: '🇧🇩' },
    { name: 'Barbados', abbr: 'BB', flag: '🇧🇧' },
    { name: 'Belarus', abbr: 'BY', flag: '🇧🇾' },
    { name: 'Belgium', abbr: 'BE', flag: '🇧🇪' },
    { name: 'Belize', abbr: 'BZ', flag: '🇧🇿' },
    { name: 'Benin', abbr: 'BJ', flag: '🇧🇯' },
    { name: 'Bermuda', abbr: 'BM', flag: '🇧🇲' },
    { name: 'Bhutan', abbr: 'BT', flag: '🇧🇹' },
    { name: 'Bolivia', abbr: 'BO', flag: '🇧🇴' },
    { name: 'Bonaire, Sint Eustatius and Saba', abbr: 'BQ', flag: '🇧🇶' },
    { name: 'Bosnia and Herzegovina', abbr: 'BA', flag: '🇧🇦' },
    { name: 'Botswana', abbr: 'BW', flag: '🇧🇼' },
    { name: 'Bouvet Island', abbr: 'BV', flag: '🇧🇻' },
    { name: 'Brazil', abbr: 'BR', flag: '🇧🇷' },
    { name: 'British Indian Ocean Territory', abbr: 'IO', flag: '🇮🇴' },
    { name: 'Brunei Darussalam', abbr: 'BN', flag: '🇧🇳' },
    { name: 'Bulgaria', abbr: 'BG', flag: '🇧🇬' },
    { name: 'Burkina Faso', abbr: 'BF', flag: '🇧🇫' },
    { name: 'Burundi', abbr: 'BI', flag: '🇧🇮' },
    { name: 'Cabo Verde', abbr: 'CV', flag: '🇨🇻' },
    { name: 'Cambodia', abbr: 'KH', flag: '🇰🇭' },
    { name: 'Cameroon', abbr: 'CM', flag: '🇨🇲' },
    { name: 'Canada', abbr: 'CA', flag: '🇨🇦' },
    { name: 'Cayman Islands', abbr: 'KY', flag: '🇰🇾' },
    { name: 'Central African Republic', abbr: 'CF', flag: '🇨🇫' },
    { name: 'Chad', abbr: 'TD', flag: '🇹🇩' },
    { name: 'Chile', abbr: 'CL', flag: '🇨🇱' },
    { name: 'China', abbr: 'CN', flag: '🇨🇳' },
    { name: 'Christmas Island', abbr: 'CX', flag: '🇨🇽' },
    { name: 'Cocos Islands', abbr: 'CC', flag: '🇨🇨' },
    { name: 'Colombia', abbr: 'CO', flag: '🇨🇴' },
    { name: 'Comoros', abbr: 'KM', flag: '🇰🇲' },
    { name: 'Congo', abbr: 'CG', flag: '🇨🇬' },
    { name: 'Congo, Democratic Republic of the', abbr: 'CD', flag: '🇨🇩' },
    { name: 'Cook Islands', abbr: 'CK', flag: '🇨🇰' },
    { name: 'Costa Rica', abbr: 'CR', flag: '🇨🇷' },
    { name: 'Cote d\'Ivoire', abbr: 'CI', flag: '🇨🇮' },
    { name: 'Croatia', abbr: 'HR', flag: '🇭🇷' },
    { name: 'Cuba', abbr: 'CU', flag: '🇨🇺' },
    { name: 'Curacao', abbr: 'CW', flag: '🇨🇼' },
    { name: 'Cyprus', abbr: 'CY', flag: '🇨🇾' },
    { name: 'Czech Republic', abbr: 'CZ', flag: '🇨🇿' },
    { name: 'Denmark', abbr: 'DK', flag: '🇩🇰' },
    { name: 'Djibouti', abbr: 'DJ', flag: '🇩🇯' },
    { name: 'Dominica', abbr: 'DM', flag: '🇩🇲' },
    { name: 'Dominican Republic', abbr: 'DO', flag: '🇩🇴' },
    { name: 'Ecuador', abbr: 'EC', flag: '🇪🇨' },
    { name: 'Egypt', abbr: 'EG', flag: '🇪🇬' },
    { name: 'El Salvador', abbr: 'SV', flag: '🇸🇻' },
    { name: 'Equatorial Guinea', abbr: 'GQ', flag: '🇬🇶' },
    { name: 'Eritrea', abbr: 'ER', flag: '🇪🇷' },
    { name: 'Estonia', abbr: 'EE', flag: '🇪🇪' },
    { name: 'Eswatini', abbr: 'SZ', flag: '🇸🇿' },
    { name: 'Ethiopia', abbr: 'ET', flag: '🇪🇹' },
    { name: 'Falkland Islands', abbr: 'FK', flag: '🇫🇰' },
    { name: 'Faroe Islands', abbr: 'FO', flag: '🇫🇴' },
    { name: 'Fiji', abbr: 'FJ', flag: '🇫🇯' },
    { name: 'Finland', abbr: 'FI', flag: '🇫🇮' },
    { name: 'France', abbr: 'FR', flag: '🇫🇷' },
    { name: 'French Guiana', abbr: 'GF', flag: '🇬🇫' },
    { name: 'French Polynesia', abbr: 'PF', flag: '🇵🇫' },
    { name: 'French Southern Territories', abbr: 'TF', flag: '🇹🇫' },
    { name: 'Gabon', abbr: 'GA', flag: '🇬🇦' },
    { name: 'Gambia', abbr: 'GM', flag: '🇬🇲' },
    { name: 'Georgia', abbr: 'GE', flag: '🇬🇪' },
    { name: 'Germany', abbr: 'DE', flag: '🇩🇪' },
    { name: 'Ghana', abbr: 'GH', flag: '🇬🇭' },
    { name: 'Gibraltar', abbr: 'GI', flag: '🇬🇮' },
    { name: 'Greece', abbr: 'GR', flag: '🇬🇷' },
    { name: 'Greenland', abbr: 'GL', flag: '🇬🇱' },
    { name: 'Grenada', abbr: 'GD', flag: '🇬🇩' },
    { name: 'Guadeloupe', abbr: 'GP', flag: '🇬🇵' },
    { name: 'Guam', abbr: 'GU', flag: '🇬🇺' },
    { name: 'Guatemala', abbr: 'GT', flag: '🇬🇹' },
    { name: 'Guernsey', abbr: 'GG', flag: '🇬🇬' },
    { name: 'Guinea', abbr: 'GN', flag: '🇬🇳' },
    { name: 'Guinea-Bissau', abbr: 'GW', flag: '🇬🇼' },
    { name: 'Guyana', abbr: 'GY', flag: '🇬🇾' },
    { name: 'Haiti', abbr: 'HT', flag: '🇭🇹' },
    { name: 'Heard Island and McDonald Islands', abbr: 'HM', flag: '🇭🇲' },
    { name: 'Holy See', abbr: 'VA', flag: '🇻🇦' },
    { name: 'Honduras', abbr: 'HN', flag: '🇭🇳' },
    { name: 'Hong Kong', abbr: 'HK', flag: '🇭🇰' },
    { name: 'Hungary', abbr: 'HU', flag: '🇭🇺' },
    { name: 'Iceland', abbr: 'IS', flag: '🇮🇸' },
    { name: 'India', abbr: 'IN', flag: '🇮🇳' },
    { name: 'Indonesia', abbr: 'ID', flag: '🇮🇩' },
    { name: 'Iran', abbr: 'IR', flag: '🇮🇷' },
    { name: 'Iraq', abbr: 'IQ', flag: '🇮🇶' },
    { name: 'Ireland', abbr: 'IE', flag: '🇮🇪' },
    { name: 'Isle of Man', abbr: 'IM', flag: '🇮🇲' },
    { name: 'Israel', abbr: 'IL', flag: '🇮🇱' },
    { name: 'Italy', abbr: 'IT', flag: '🇮🇹' },
    { name: 'Jamaica', abbr: 'JM', flag: '🇯🇲' },
    { name: 'Japan', abbr: 'JP', flag: '🇯🇵' },
    { name: 'Jersey', abbr: 'JE', flag: '🇯🇪' },
    { name: 'Jordan', abbr: 'JO', flag: '🇯🇴' },
    { name: 'Kazakhstan', abbr: 'KZ', flag: '🇰🇿' },
    { name: 'Kenya', abbr: 'KE', flag: '🇰🇪' },
    { name: 'Kiribati', abbr: 'KI', flag: '🇰🇮' },
    { name: 'Korea', abbr: 'KR', flag: '🇰🇷' },
    { name: 'Korea, Democratic People\'s Republic of', abbr: 'KP', flag: '🇰🇵' },
    { name: 'Kosovo', abbr: 'XK', flag: '🇽🇰' },
    { name: 'Kuwait', abbr: 'KW', flag: '🇰🇼' },
    { name: 'Kyrgyzstan', abbr: 'KG', flag: '🇰🇬' },
    { name: 'Lao People\'s Democratic Republic', abbr: 'LA', flag: '🇱🇦' },
    { name: 'Latvia', abbr: 'LV', flag: '🇱🇻' },
    { name: 'Lebanon', abbr: 'LB', flag: '🇱🇧' },
    { name: 'Lesotho', abbr: 'LS', flag: '🇱🇸' },
    { name: 'Liberia', abbr: 'LR', flag: '🇱🇷' },
    { name: 'Libya', abbr: 'LY', flag: '🇱🇾' },
    { name: 'Liechtenstein', abbr: 'LI', flag: '🇱🇮' },
    { name: 'Lithuania', abbr: 'LT', flag: '🇱🇹' },
    { name: 'Luxembourg', abbr: 'LU', flag: '🇱🇺' },
    { name: 'Macao', abbr: 'MO', flag: '🇲🇴' },
    { name: 'Madagascar', abbr: 'MG', flag: '🇲🇬' },
    { name: 'Malawi', abbr: 'MW', flag: '🇲🇼' },
    { name: 'Malaysia', abbr: 'MY', flag: '🇲🇾' },
    { name: 'Maldives', abbr: 'MV', flag: '🇲🇻' },
    { name: 'Mali', abbr: 'ML', flag: '🇲🇱' },
    { name: 'Malta', abbr: 'MT', flag: '🇲🇹' },
    { name: 'Marshall Islands', abbr: 'MH', flag: '🇲🇭' },
    { name: 'Martinique', abbr: 'MQ', flag: '🇲🇶' },
    { name: 'Mauritania', abbr: 'MR', flag: '🇲🇷' },
    { name: 'Mauritius', abbr: 'MU', flag: '🇲🇺' },
    { name: 'Mayotte', abbr: 'YT', flag: '🇾🇹' },
    { name: 'Mexico', abbr: 'MX', flag: '🇲🇽' },
    { name: 'Micronesia', abbr: 'FM', flag: '🇫🇲' },
    { name: 'Moldova', abbr: 'MD', flag: '🇲🇩' },
    { name: 'Monaco', abbr: 'MC', flag: '🇲🇨' },
    { name: 'Mongolia', abbr: 'MN', flag: '🇲🇳' },
    { name: 'Montenegro', abbr: 'ME', flag: '🇲🇪' },
    { name: 'Montserrat', abbr: 'MS', flag: '🇲🇸' },
    { name: 'Morocco', abbr: 'MA', flag: '🇲🇦' },
    { name: 'Mozambique', abbr: 'MZ', flag: '🇲🇿' },
    { name: 'Myanmar', abbr: 'MM', flag: '🇲🇲' },
    { name: 'Namibia', abbr: 'NA', flag: '🇳🇦' },
    { name: 'Nauru', abbr: 'NR', flag: '🇳🇷' },
    { name: 'Nepal', abbr: 'NP', flag: '🇳🇵' },
    { name: 'Netherlands', abbr: 'NL', flag: '🇳🇱' },
    { name: 'New Caledonia', abbr: 'NC', flag: '🇳🇨' },
    { name: 'New Zealand', abbr: 'NZ', flag: '🇳🇿' },
    { name: 'Nicaragua', abbr: 'NI', flag: '🇳🇮' },
    { name: 'Niger', abbr: 'NE', flag: '🇳🇪' },
    { name: 'Nigeria', abbr: 'NG', flag: '🇳🇬' },
    { name: 'Niue', abbr: 'NU', flag: '🇳🇺' },
    { name: 'Norfolk Island', abbr: 'NF', flag: '🇳🇫' },
    { name: 'North Macedonia', abbr: 'MK', flag: '🇲🇰' },
    { name: 'Northern Mariana Islands', abbr: 'MP', flag: '🇲🇵' },
    { name: 'Norway', abbr: 'NO', flag: '🇳🇴' },
    { name: 'Oman', abbr: 'OM', flag: '🇴🇲' },
    { name: 'Pakistan', abbr: 'PK', flag: '🇵🇰' },
    { name: 'Palau', abbr: 'PW', flag: '🇵🇼' },
    { name: 'Palestine', abbr: 'PS', flag: '🇵🇸' },
    { name: 'Panama', abbr: 'PA', flag: '🇵🇦' },
    { name: 'Papua New Guinea', abbr: 'PG', flag: '🇵🇬' },
    { name: 'Paraguay', abbr: 'PY', flag: '🇵🇾' },
    { name: 'Peru', abbr: 'PE', flag: '🇵🇪' },
    { name: 'Philippines', abbr: 'PH', flag: '🇵🇭' },
    { name: 'Pitcairn', abbr: 'PN', flag: '🇵🇳' },
    { name: 'Poland', abbr: 'PL', flag: '🇵🇱' },
    { name: 'Portugal', abbr: 'PT', flag: '🇵🇹' },
    { name: 'Puerto Rico', abbr: 'PR', flag: '🇵🇷' },
    { name: 'Qatar', abbr: 'QA', flag: '🇶🇦' },
    { name: 'Reunion', abbr: 'RE', flag: '🇷🇪' },
    { name: 'Romania', abbr: 'RO', flag: '🇷🇴' },
    { name: 'Russian Federation', abbr: 'RU', flag: '🇷🇺' },
    { name: 'Rwanda', abbr: 'RW', flag: '🇷🇼' },
    { name: 'Saint Barthelemy', abbr: 'BL', flag: '🇧🇱' },
    { name: 'Saint Helena', abbr: 'SH', flag: '🇸🇭' },
    { name: 'Saint Kitts and Nevis', abbr: 'KN', flag: '🇰🇳' },
    { name: 'Saint Lucia', abbr: 'LC', flag: '🇱🇨' },
    { name: 'Saint Martin', abbr: 'MF', flag: '🇲🇫' },
    { name: 'Saint Pierre and Miquelon', abbr: 'PM', flag: '🇵🇲' },
    { name: 'Saint Vincent and the Grenadines', abbr: 'VC', flag: '🇻🇨' },
    { name: 'Samoa', abbr: 'WS', flag: '🇼🇸' },
    { name: 'San Marino', abbr: 'SM', flag: '🇸🇲' },
    { name: 'Sao Tome and Principe', abbr: 'ST', flag: '🇸🇹' },
    { name: 'Saudi Arabia', abbr: 'SA', flag: '🇸🇦' },
    { name: 'Senegal', abbr: 'SN', flag: '🇸🇳' },
    { name: 'Serbia', abbr: 'RS', flag: '🇷🇸' },
    { name: 'Seychelles', abbr: 'SC', flag: '🇸🇨' },
    { name: 'Sierra Leone', abbr: 'SL', flag: '🇸🇱' },
    { name: 'Singapore', abbr: 'SG', flag: '🇸🇬' },
    { name: 'Sint Maarten', abbr: 'SX', flag: '🇸🇽' },
    { name: 'Slovakia', abbr: 'SK', flag: '🇸🇰' },
    { name: 'Slovenia', abbr: 'SI', flag: '🇸🇮' },
    { name: 'Solomon Islands', abbr: 'SB', flag: '🇸🇧' },
    { name: 'Somalia', abbr: 'SO', flag: '🇸🇴' },
    { name: 'South Africa', abbr: 'ZA', flag: '🇿🇦' },
    { name: 'South Georgia and the South Sandwich Islands', abbr: 'GS', flag: '🇬🇸' },
    { name: 'South Sudan', abbr: 'SS', flag: '🇸🇸' },
    { name: 'Spain', abbr: 'ES', flag: '🇪🇸' },
    { name: 'Sri Lanka', abbr: 'LK', flag: '🇱🇰' },
    { name: 'Sudan', abbr: 'SD', flag: '🇸🇩' },
    { name: 'Suriname', abbr: 'SR', flag: '🇸🇷' },
    { name: 'Svalbard and Jan Mayen', abbr: 'SJ', flag: '🇸🇯' },
    { name: 'Sweden', abbr: 'SE', flag: '🇸🇪' },
    { name: 'Switzerland', abbr: 'CH', flag: '🇨🇭' },
    { name: 'Syrian Arab Republic', abbr: 'SY', flag: '🇸🇾' },
    { name: 'Taiwan', abbr: 'TW', flag: '🇹🇼' },
    { name: 'Tajikistan', abbr: 'TJ', flag: '🇹🇯' },
    { name: 'Tanzania', abbr: 'TZ', flag: '🇹🇿' },
    { name: 'Thailand', abbr: 'TH', flag: '🇹🇭' },
    { name: 'Timor-Leste', abbr: 'TL', flag: '🇹🇱' },
    { name: 'Togo', abbr: 'TG', flag: '🇹🇬' },
    { name: 'Tokelau', abbr: 'TK', flag: '🇹🇰' },
    { name: 'Tonga', abbr: 'TO', flag: '🇹🇴' },
    { name: 'Trinidad and Tobago', abbr: 'TT', flag: '🇹🇹' },
    { name: 'Tunisia', abbr: 'TN', flag: '🇹🇳' },
    { name: 'Turkey', abbr: 'TR', flag: '🇹🇷' },
    { name: 'Turkmenistan', abbr: 'TM', flag: '🇹🇲' },
    { name: 'Turks and Caicos Islands', abbr: 'TC', flag: '🇹🇨' },
    { name: 'Tuvalu', abbr: 'TV', flag: '🇹🇻' },
    { name: 'Uganda', abbr: 'UG', flag: '🇺🇬' },
    { name: 'Ukraine', abbr: 'UA', flag: '🇺🇦' },
    { name: 'United Arab Emirates', abbr: 'AE', flag: '🇦🇪' },
    { name: 'United Kingdom', abbr: 'GB', flag: '🇬🇧' },
    { name: 'United States', abbr: 'US', flag: '🇺🇸' },
    { name: 'United States Minor Outlying Islands', abbr: 'UM', flag: '🇺🇲' },
    { name: 'Uruguay', abbr: 'UY', flag: '🇺🇾' },
    { name: 'Uzbekistan', abbr: 'UZ', flag: '🇺🇿' },
    { name: 'Vanuatu', abbr: 'VU', flag: '🇻🇺' },
    { name: 'Venezuela', abbr: 'VE', flag: '🇻🇪' },
    { name: 'Vietnam', abbr: 'VN', flag: '🇻🇳' },
    { name: 'Virgin Islands (British)', abbr: 'VG', flag: '🇻🇬' },
    { name: 'Virgin Islands (U.S.)', abbr: 'VI', flag: '🇻🇮' },
    { name: 'Wallis and Futuna', abbr: 'WF', flag: '🇼🇫' },
    { name: 'Western Sahara', abbr: 'EH', flag: '🇪🇭' },
    { name: 'Yemen', abbr: 'YE', flag: '🇾🇪' },
    { name: 'Zambia', abbr: 'ZM', flag: '🇿🇲' },
    { name: 'Zimbabwe', abbr: 'ZW', flag: '🇿🇼' },
  ];
  
  
  document.addEventListener("DOMContentLoaded", function () {
    const input = document.getElementById("countryInput");
    const countryList = document.getElementById("countryList");
  
    input.addEventListener("input", function () {
      const inputValue = input.value.trim().toLowerCase();
      const filteredCountries = countries.filter(country =>
        country.name.toLowerCase().startsWith(inputValue)
      );
  
      renderCountryList(filteredCountries);
    });
  
    countryList.addEventListener("click", function (event) {
      if (event.target.tagName === "LI") {
        input.value = event.target.textContent;
        countryList.innerHTML = ""; // Clear the list after selecting a country
      }
    });
  
    function renderCountryList(countries) {
      countryList.innerHTML = ""; // Clear the list before re-rendering
      countries.forEach(country => {
        const listItem = document.createElement("li");
  
        const flagSpan = document.createElement("span");
        flagSpan.textContent = country.flag;
        listItem.appendChild(flagSpan);
  
        const nameSpan = document.createElement("span");
        nameSpan.textContent = country.name;
        listItem.appendChild(nameSpan);
  
        const abbrSpan = document.createElement("span");
        abbrSpan.textContent = `(${country.abbr})`;
        listItem.appendChild(abbrSpan);
  
        countryList.appendChild(listItem);
      });
    }
  });
  